version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      maven: 3.9
    commands:
      - echo "Install phase - Maven and Java are ready"
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - mvn clean
  build:
    commands:
      - echo "Building project..."
      - mvn package -DskipTests=true
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - target/*.war
