version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "=== INSTALL PHASE ==="
      - mvn -v
  pre_build:
    commands:
      - echo "=== PRE-BUILD PHASE ==="
      - mvn clean
  build:
    commands:
      - echo "=== BUILD PHASE ==="
      - mvn package -DskipTests=true
  post_build:
    commands:
      - echo "=== POST-BUILD PHASE ==="
      - echo "Build completed on `date`"
artifacts:
  files:
    - target/*.war
